zuul: easy update procedure
Juniper/contrail-windows-docs pull request #17
Opened 2018-07-02 14:45 UTC by sodar

Documentation for easier Zuul update procedure. By easier I mean, it depends solely playbooks on `contrail-windows-ci` and does not require manual patching.

2018-07-02 14:52 UTC, m-kostrzewa approved these changes

2018-07-02 14:52 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    - Please contact with Windows CI team
> Please contact ~~with~~ Windows CI team

2018-07-02 14:52 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    - Please contact with Windows CI team
as above

2018-07-02 14:52 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +1.  Install required `apt` dependencies
Where?

2018-07-02 14:52 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    If a playbook run completed successfully, then output should be following:
> Verify that the run completed successfully. The output should be following and `failed` task count must equal zero.

2018-07-02 14:52 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    git log  # verify commit log
Make sure
verify

^ those are too broad, I wouldn't know what to look for

2018-07-02 14:54 UTC, jacek-izykowski requested changes

2018-07-02 14:54 UTC, jacek-izykowski commented on doc/ci_admin_guide/Update_Zuul.md
> +    source venv/bin/active
It's `ativate`.

2018-07-02 14:54 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    source venv/bin/active
:ghost:

2018-07-02 16:17 UTC, m-kostrzewa approved these changes

2018-07-02 16:17 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +    - It will serve as Ansible control maching
machine*

2018-07-03 12:33 UTC, jacek-izykowski approved these changes

2018-07-04 10:20 UTC, merged