Merge prod update
Juniper/contrail-windows-docs pull request #22
Opened 2018-07-16 13:14 UTC by sodar

2018-07-17 10:25 UTC, m-kostrzewa requested changes

2018-07-17 10:25 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +1. **[ONLY IF UPDATING FROM `production` branch]** Checkout `production` branch
It's not clear what this means. Maybe something like:

```
1. Checkout branch that you want to use for configuring Zuul. For example, to checkout production branch: ...
```

2018-07-17 10:25 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +1.  Verify that `development` (or `production`) branch contains PRs with required changes to Zuul configuration
If we give an example for production, let's stick to having production come up first (out of parentheses)

```
Verify that `production` (or `development`)...
```

2018-07-17 10:25 UTC, m-kostrzewa commented on doc/ci_admin_guide/Update_Zuul.md
> +1. **[ONLY IF UPDATING FROM `production` branch]** Checkout `production` branch
Otherwise, it could mean that this step should only be performed for production branch.

2018-07-17 10:28 UTC, jacek-izykowski reviewed
Readability of `**[ONLY IF UPDATING FROM production branch]** Checkout production branch` could be improved as MKos suggests. However I expect everyone to understand what's this point about.

2018-07-25 12:33 UTC, m-kostrzewa approved these changes

2018-07-26 16:10 UTC, merged