add contrail-status usage
Juniper/contrail-windows-docs pull request #91
Opened 2018-10-25 18:39 UTC by sagarkchitnis

Change-Id: Ie54da42a0cfb10678ef610a05dc34096f2e2bd46

Write-up for script

2018-10-26 10:34 UTC, m-kostrzewa requested changes
The link was incorrect

2018-10-26 10:34 UTC, m-kostrzewa commented on doc/Known_issues/Troubleshooting.md
> +Run contrail-status.ps1 from https://github.com/Juniper/contrail-windows/tree/scripts
```suggestion
Run contrail-status.ps1 from https://github.com/Juniper/contrail-windows/tree/master/scripts
```

2018-10-31 01:48 UTC, sagarkchitnis commented on doc/Known_issues/Troubleshooting.md
> +Run contrail-status.ps1 from https://github.com/Juniper/contrail-windows/tree/scripts
fixed

2018-10-31 09:14 UTC, m-kostrzewa approved these changes

2018-10-31 09:14 UTC, merged